[[main]]
  name = "AI alati"
  pageRef = "ai-alati"
  weight = 10

[[main]]
  name = "Vještine"
  pageRef = "vjestine"
  weight = 20

[[main]]
  name = "Karijera"
  pageRef = "karijera"
  weight = 30

[[main]]
  name = "Projekti"
  pageRef = "projekti"
  weight = 40

[[main]]
  name = "Učenje"
  pageRef = "ucenje"
  weight = 50

[[main]]
  name = "O projektu"
  pageRef = "o-projektu"
  weight = 60