[[main]]
  name = "Članci"
  pageRef = "clanci"
  weight = 10


[[main]]
  name = "Usluge"
  pageRef = "usluge"
  weight = 30

[[main]]
  name = "Newsletter"
  url = "/#newsletter"
  weight = 99

[[main]]
  name = "Traži"
  weight = 50
  [main.params]
    action = "search"
